clinica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('', include('compartido.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

productos/urls.py
# Django
from django.urls import path

# Vistas
from .views import productos, pedidos, detallePedidos as detalles, categorias

app_name = 'productos'

URLS_PRODUCTOS = [
    path('', productos.Listar.as_view(), name='lista'),
    path('agregar/', productos.Agregar.as_view(), name='agregar'),
    path('detalle/<uuid:pk>', productos.Detalle.as_view(), name='detalle'),
    path('editar/<uuid:pk>', productos.Editar.as_view(), name='editar'),
    path('eliminar/<uuid:pk>', productos.Eliminar.as_view(), name='eliminar'),
]

URLS_CATEGORIAS = [
    path('categorias/', categorias.Agregar.as_view(), name='categorias'),
    path('categorias/editar/<int:pk>', categorias.Editar.as_view(), name='editar_categoria'),
    path('categorias/eliminar/<int:pk>', categorias.Eliminar.as_view(), name='eliminar_categoria')
]


URLS_PEDIDOS = [
    path('pedidos/', pedidos.Listar.as_view(), name='lista_pedidos'),
    path('pedidos/agregar/', pedidos.Agregar.as_view(), name='agregar_pedido'),
    path('pedidos/editar/<uuid:pk>', pedidos.Editar.as_view(), name='editar_pedido'),
    path('pedidos/eliminar/<uuid:pk>', pedidos.Eliminar.as_view(), name='eliminar_pedido')
]

URLS_DETALLES = [
    path('pedidos/agregar_producto/<uuid:pk>', detalles.Agregar.as_view(), name='agregar_detalle'),
    path('pedidos/eliminar_producto/<uuid:pk>', detalles.Eliminar.as_view(), name='eliminar_detalle'),
    path('pedidos/editar_producto/<uuid:pk>', detalles.Editar.as_view(), name='editar_detalle')
]

urlpatterns = URLS_PRODUCTOS + URLS_CATEGORIAS + URLS_PEDIDOS + URLS_DETALLES

productos/models/modelo_producto.py
# Python
from datetime import date

# Django
from django.db import models

# Modelos
from compartido.modelo_base import ModeloBase


class Categoria(models.Model):
    nombre = models.CharField(max_length=250, verbose_name="Nombre de la categoria")

    class Meta:
        db_table = "categoria"
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.nombre


class Producto(ModeloBase):
    """ 
    Esta clase contiene la logica para persistir productos en el sistema.
    """

    LADO_OPCIONES = (
        ('izquierdo', 'Izquierdo'),
        ('derecho', 'Derecho')
    )

    DISTANCIA_OPCIONES = (
        ('lejos', 'Lejos'),
        ('cerca', 'Cerca')
    )

    nombre = models.CharField(max_length=250, verbose_name="Nombre", unique=True)
    cod_producto = models.CharField(max_length=100, verbose_name="Código del producto", blank=True, null=True)
    precio = models.DecimalField(max_digits=14, decimal_places=2, default=0.0, verbose_name="Precio")
    imagen = models.ImageField(upload_to='productos/img/', blank=True, null=True, verbose_name="Imagen del producto")
    stock = models.PositiveIntegerField(blank=True, null=True, verbose_name="Cantidad", default=1)
    categoria = models.ForeignKey(
        Categoria, 
        on_delete=models.CASCADE, 
        blank=True,
        null=True,
        verbose_name="Categoria",
        )
    armazon = models.BooleanField(default=False, verbose_name="Armazon")
    lente = models.BooleanField(default=False, verbose_name="Es un lente")
    lado = models.CharField(
        max_length=9,
        choices=LADO_OPCIONES,
        default='izquierdo',
        blank=True,
        null=True,
        verbose_name="Para que ojo"
        )
    distancia = models.CharField(
        max_length=5,
        choices=DISTANCIA_OPCIONES,
        default='lejos',
        blank=True,
        null=True,
        verbose_name="Distancia"
    )
        
    class Meta:
        db_table = "producto"
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        if self.lente == False:
            self.distancia = None
            self.lado = None
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.nombre} | stock: {self.stock} | $ {self.precio} "

productos/forms.py
# Django
from django.forms import ModelForm

# Modelos
from .models import *
from usuarios.models import Usuario

class FormularioProducto(ModelForm):
    
    class Meta:
        model = Producto
        fields = '__all__'


class FormularioPedido(ModelForm):

    class Meta:
        model = Pedido
        fields = ('estado', 'paciente', 'tipo_de_pago', 'vendedor')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['vendedor'].queryset = Usuario.objects.filter(rol='V')

#---------------------------------------
class FormularioDetallePedido(ModelForm):

    class Meta:
        model = DetallePedido
        fields = ('producto', 'cantidad')


class FormularioCategoria(ModelForm):

    class Meta:
        model = Categoria
        fields = '__all__'

productos/views/categorias.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic

# Modelos
from ..models import Categoria, Producto
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioCategoria


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega una nueva categoria.
    """
    model = Categoria
    form_class = FormularioCategoria
    template_name = 'clinica/productos/categorias.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Cargó una categoria'
        )
        messages.success(
            self.request,
            'Categoria cargada!'
        )
        return reverse_lazy('productos:categorias')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Categorias'
        contexto['categorias'] = Categoria.objects.all()
        return contexto



class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de una determinada categoria.
    """
    model = Categoria
    form_class = FormularioCategoria
    template_name = 'clinica/productos/categorias.html'       

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Modificó una categoria'
        )
        messages.success(
            self.request,
            'Categoria modificada!'
        )
        return reverse_lazy('productos:categorias') 

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Categorias'
        contexto['editar'] = True
        contexto['productos'] = Producto.objects.filter(categoria=self.kwargs['pk'])
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """ 
    Elimina una categoria del sistema.
    """
    model = Categoria
    template_name = 'componentes/delete.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó una categoria'
        )
        messages.success(
            self.request,
            'Categoria eliminada!'
        )
        return reverse_lazy('productos:categorias')


    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar {self.object}'
        contexto['url_volver'] = reverse_lazy('productos:categorias')
        return contexto

productos/views/detallePedidos.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic

# Modelos
from ..models import DetallePedido, Pedido
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioDetallePedido


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega un nuevo producto a la lista de productos de un pedido y puede 
    retornar a la lista o a un nuevo formulario para agregar otro producto más.
    """
    model = DetallePedido
    form_class = FormularioDetallePedido
    template_name = 'clinica/pedidos/detallePedido/form_detalle_pedido.html'

    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Agregó un producto a un pedido'
        )
        messages.success(
            self.request,
            'Producto agregado al carrito!'
        )
        form.instance.pedido = Pedido.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('productos:editar_pedido', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        pedido = Pedido.objects.get(pk=self.kwargs['pk'])
        contexto = super().get_context_data(**kwargs)
        contexto['url_volver'] = self.get_success_url
        contexto['titulo'] = f'Pedido de {pedido.paciente}'
        return contexto


class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de un determinado producto de la lista de compra.
    """
    model = DetallePedido
    form_class = FormularioDetallePedido
    template_name = 'clinica/pedidos/detallePedido/form_detalle_pedido.html'          

    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Modificó los productos de un pedido'
        )
        messages.success(
            self.request,
            'Carrito actualizado!'
        )
        p = DetallePedido.objects.get(id=self.kwargs['pk'])
        form.instance.pedido = Pedido.objects.get(pk=p.pedido_id)
        return super().form_valid(form)

    def get_success_url(self):
        pedido = self.request.GET.get('pedido')
        return reverse_lazy('productos:editar_pedido', kwargs={'pk': pedido})

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Producto para {self.object.pedido}'
        contexto['url_volver'] = self.get_success_url
        contexto['editar'] = True
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """
    Elimina un producto de la lista de compra.
    """
    model = DetallePedido
    template_name = 'componentes/delete.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó un producto de un pedido'
        )
        messages.success(
            self.request,
            'Se elimino un producto del carrito!'
        )
        pedido = self.request.GET.get('pedido')
        return reverse_lazy('productos:editar_pedido', kwargs={'pk': pedido})

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar {self.object}'
        # hago de vuelta esto porque si llamo a get_success_url me manda el mensaje 2 veces
        pedido = self.request.GET.get('pedido')
        contexto['url_volver'] = reverse_lazy('productos:editar_pedido', kwargs={'pk': pedido})
        return contexto

productos/views/pedidos.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic

# Modelos
from ..models import Pedido, Producto, DetallePedido
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioPedido

class Listar(LoginRequiredMixin, generic.ListView):
    """
    Lista todos los pedidos cargados en el sistema. 
    """
    model = Pedido
    template_name = 'clinica/pedidos/lista_pedidos.html'
    context_object_name = 'Pedidos'
    paginate_by = 5
    # page_kwarg

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Lista de pedidos'
        contexto['buscar'] = 'Ingresa el nombre de alǵun paciente'
        contexto['cantidad'] = Pedido.objects.all().count()
        return contexto


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega un nuevo pedido y retorna a la lista de pacientes.
    """
    model = Pedido
    form_class = FormularioPedido
    template_name = 'clinica/pedidos/form_pedido.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Cargó un pedido'
        )
        messages.success(
            self.request,
            'Pedido cargado!'
        )
        ultimo = Pedido.objects.last()
        return reverse_lazy('productos:editar_pedido', kwargs={'pk': ultimo.id})

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Agregar pedido'
        return contexto


class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de un determinado pedido.
    """
    model = Pedido
    form_class = FormularioPedido
    template_name = 'clinica/pedidos/form_pedido.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Modificó un pedido'
        )
        messages.success(
            self.request,
            'Pedido modificado!'
        )
        return reverse_lazy('productos:lista_pedidos')            

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Pedido de {self.object.paciente}'
        contexto['cantidad'] = DetallePedido.objects.filter(pedido=self.kwargs['pk']).count()
        contexto['lista_productos'] = DetallePedido.objects.filter(pedido=self.kwargs['pk'])
        contexto['editar'] = True
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """ 
    Elimina un pedido del sistema.
    """
    model = Pedido
    template_name = 'componentes/delete.html'
    
    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó un pedido'
        )
        messages.success(
            self.request,
            'Pedido eliminado!'
        )
        return reverse_lazy('productos:lista_pedidos')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar {self.object}'
        contexto['url_volver'] = reverse_lazy('productos:lista_pedidos')
        return contexto

templates/clinica/productos/categorias.html
{% extends 'layout.html' %}
{% load usuarios_tags %}
{% load widget_tweaks %}

{% block content %}
    {% if user|sector:"Venta" or user|sector:"Gerencia" %}
        <form method="post">
            {% csrf_token %}
            <div class="container pt-3">
                <h3 class="display-5 text-center my-3">
                    {{titulo}}
                    {% if categorias %}
                        <span class="badge bg-warning rounded-circle align-text-bottom">{{categorias.count}}</span>
                    {% endif %}
                </h3>
                
                {% include 'componentes/forms_errors.html' %}

                <div class="row d-flex justify-content-center m-3">
                    <!-- Nombre de la categoria -->
                    <div class="col-md-6">
                        <div class="my-3">
                            <label class="form-label">{{form.nombre.label|upper}}</label>
                            {{form.nombre|attr:"autocomplete:off"|attr:"autofocus:on"|add_class:'form-control rounded-pill'}}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="d-flex justify-content-center my-3">
                        <div class="btn-group shadow-sm" role="group" aria-label="Basic outlined example">
                            {% if editar %}
                                <a href="{% url 'productos:categorias' %}" type="button" class="btn btn-outline-primary">
                                    <i class="fas fa-angle-double-left text-info"></i> Volver
                                </a>
                                <a href="{% url 'productos:eliminar_categoria' object.id %}" type="button" 
                                class="btn btn-outline-primary">
                                    <i class="fas fa-times text-danger"></i> Eliminar
                                </a>
                            {% else %}
                                <a href="{% url 'productos:lista' %}" type="button" class="btn btn-outline-primary">
                                    <i class="fas fa-angle-double-left text-info"></i> Volver
                                </a>
                            {% endif %}
                            <button type="submit" class="btn btn-outline-primary">
                                <i class="fas fa-check text-ifno"></i> Guardar
                            </button>
                        </div>
                    </div>
                </div>

                <div class="row d-flex justify-content-center my-4">
                    <div class="col-md-6">   
                        {% if editar %}
                            {% if productos %}
                                <ul class="list-group list-group-flush">
                                    {% for producto in productos %}
                                        <li class="list-group-item bg-transparent text-center">
                                            {{producto.nombre}}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <p class="text-center">No hay productos con esta categoria aún</p>
                            {% endif %}
                        {% else %}
                            {% if categorias %}
                                <div class="table-responsive">
                                    <table class="table table-borderless">
                                        <tbody>
                                            {% for categoria in categorias %}
                                                <tr>
                                                    <td class="text-center">
                                                        <p class="border-bottom border-verde border-2">{{categoria}}</p>
                                                    </td>
                                                    <td class="text-center">
                                                        <a href="{% url 'productos:editar_categoria' categoria.id %}">
                                                            <i class="fas fa-search text-dark"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div> 
                            {% else %}
                                <h1 class="text-center my-3 lead">No hay categorias aún</h1>                         
                            {% endif %}
                        {% endif %}    
                    </div>
                </div>
            </div>
        </form>
    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-8">
                <h1 class="text-center my-5 lead">
                    No tienes permiso para cargar o modificar las categorias
                </h1>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/clinica/productos/detalle_producto.html
{% extends 'layout.html' %} 
{% load usuarios_tags %}
{% load static %} 

{% block content %}
  {% if user|sector:"Venta" or user|sector:"Gerencia" %}
    <div class="row">
      <div class="col-sm-6">
        <div class="card bg-transparent border-0 my-3">
          {% if Producto.imagen %}
            <img src="{{Producto.imagen.url}}" alt="Imagen" 
            class="card-img-top img-fluid align-self-center shadow default imagen">
          {% else %}
          <img src="{% static 'img/default.svg' %}" alt="Imagen" class="card-img-top img-fluid default">
          {% endif %}
          <div class="card-body">
            {% if Producto.categoria %}
            <h3 class="text-center bg-verde bg-gradient border mb-0">{{Producto.categoria}}</h3>
            {% else %}
              <h3 class="text-center bg-verde bg-gradient border mb-1">Sin categoria...</h3>
            {% endif %}
            {% if Producto.lente %}
              <h3 class="text-center bg-warning bg-gradient border">
                  Lente {{Producto.get_lado_display}}, para ver {{Producto.get_distancia_display}}
              </h3>
            {% endif%}
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <h1 class="text-center border-bottom border-verde border-3">
            {{Producto.nombre}} <span><i class="fas fa-dollar-sign text-success"></i></span> {{Producto.precio}} 
          </h1>
          {% if Producto.armazon %}
            <h3 class="text-center bg-success border">INCLUYE ARMAZON</h3>
          {% else %}
            <h3 class="text-center bg-danger border text-white">NO INCLUYE ARMAZON</h3>
          {% endif %}
          {% if Producto.stock > 0 %}
            <h3 class="text-center text-muted">
              Hay 
                {% if Producto.stock < 10 %}
                  {% if Producto.stock > 5 %}
                    <span class="border-bottom border-warning border-2">{{Producto.stock}}</span>
                  {% else %}
                  <span class="border-bottom border-danger border-2">{{Producto.stock}}</span>
                  {% endif %}
                {% else %}
                <span class="border-bottom border-primary border-2">{{Producto.stock}}</span>
                {% endif %}
              unidades
            </h3>
          {% else %}
          {% endif %}
      </div>
      <br>
      </div>
      <div class="d-flex justify-content-center my-4">
        <div class="btn-group shadow-sm" role="group" aria-label="Basic outlined example">
          <a href="{% url 'productos:lista' %}" type="button" class="btn btn-outline-primary">
            <i class="fas fa-angle-double-left text-info"></i>
            Volver
          </a>
          <a href="{% url 'productos:editar' object.id %}" type="button" class="btn btn-outline-primary">
            <i class="fas fa-edit text-info"></i>
            Editar
          </a>
          <a href="{% url 'productos:eliminar' object.id %}" type="button" class="btn btn-outline-primary">
            <i class="fas fa-times text-danger"></i>
            Quitar
          </a>
        </div>
      </div>
    </div>
  {% else %}
    <div class="row d-flex justify-content-center">
        <div class="col-8">
            <h1 class="text-center my-5 lead">
                No tienes permiso para ver los detalles de los productos
            </h1>
        </div>
    </div>
  {% endif %}
{% endblock %} 

templates/clinica/productos/lista_productos.html
{% extends 'layout.html' %}
{% load usuarios_tags %} 
{% load static %} 

{% block content %}
    {% if user|sector:"Venta" or user|sector:"Gerencia" %}
        {% include 'componentes/buscar_form.html' %}
        <div class="row">
            <div class="col-sm-3">
                <!-- Turnos del doctor -->
                <div class="my-3 p-3 bg-info rounded bg-gradient shadow-lg">
                    <ul class="list-group list-group-flush">
                        {% if categorias %}
                            <form class="text-center text-md-left">
                                <li class="list-group-item bg-transparent border-0">
                                    <a href="{% url 'productos:lista' %}" 
                                    type="submit" style="text-decoration: none; color: white;">
                                            TODOS
                                    </a>
                                </li>
                                {% for categoria in categorias %}
                                    <li class="list-group-item bg-transparent border-0">
                                        <a href="{% url 'productos:lista' %}?categoria={{categoria}}" 
                                        type="submit" style="text-decoration: none; color: white;">
                                                {{categoria|upper}}
                                        </a>
                                    </li>
                                {% endfor %}
                            </form>
                        {% else %}
                        <a type="buttom" class="btn text-dark" href="{% url 'productos:categorias' %}">
                            <li class="list-group-item d-flex justify-content-between align-items-center bg-transparent text-white h5">
                                No hay categorias<i class="fas fa-plus text-success ml-2"></i>
                            </li>
                        </a>
                        {% endif %}
                    </ul>
                </div>
            </div>

            <div class="col-sm-9">
                <div class="table-responsive bg-white my-3 p-3 rounded shadow-lg">
                    <div class="row mb-2">
                        <div class="col-6">
                            <h6 class="border-bottom pb-2 mb-0">
                                {{titulo}}
                                {% if cantidad %}
                                <span class="badge bg-warning rounded-pill align-text-bottom">{{cantidad}}</span>
                                {% endif %}
                            </h6>
                        </div>
                        <div class="col-6">
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <a type="buttom" class="btn btn-success btn-sm text-dark" href="{% url 'productos:agregar' %}">
                                    <i class="fas fa-plus"></i>
                                    Agregar
                                </a>
                            </div>
                        </div>
                    </div>
                    {% if Productos %}
                        <table class="table display table-bordered  table-striped table-hover table-sm id" class="stripe row-border order-column nowrap">
                            <thead>
                                <tr class="text-center table-primary">
                                    <th>Nombre</th>
                                    <th>Precio</th>
                                    <th>Stock</th>
                                    <th>Prox.Venc.</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for producto in Productos %}
                                    <tr class="text-center">
                                        <td>{{producto.nombre}}</td>
                                        <td>           
                                            <i class="fas fa-dollar-sign text-success"></i>
                                            {{producto.precio}}
                                        </td>
                                        <td
                                            {% if producto.stock <= 25 and producto.stock > 10 %}
                                                class="badge text-dark bg-warning rounded-circle"
                                            {% else %}
                                                {% if producto.stock <= 10 %}
                                                    class="badge text-white bg-danger rounded-circle"
                                                {% endif %}
                                            {% endif%}>
                                            {{producto.stock}}
                                        </td>
                                        <td>
                                            {% if producto.ultimo_vencimiento %}
                                                {{producto.ultimo_vencimiento}}
                                            {% else %}
                                                -
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="btn btn-sm d-flex align-self-center" href="{% url 'productos:detalle' producto.id %}">
                                            <i class="fas fa-search"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %} 
                            </tbody>
                        </table>
                    {% else %}
                        <h1 class="text-center my-3 lead">No hay productos aún</h1>
                    {% endif %}
                </div>
                {% include 'componentes/paginacion.html' %}
            </div>
        </div>
    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-8">
                <h1 class="text-center my-5 lead">No tienes permiso para ver los productos</h1>
            </div>
        </div>
    {% endif %}
{% endblock %}