clinica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('', include('compartido.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pacientes/urls.py
# Django
from django.urls import path

# Vistas

from .views import pacientes, observaciones, turnos

app_name = 'pacientes'

URLS_PACIENTES = [
    path('', pacientes.Listar.as_view(), name='lista'),
    path('agregar/', pacientes.Agregar.as_view(), name='agregar'),
    path('detalle/<uuid:pk>', pacientes.Detalle.as_view(), name='detalle'),
    path('editar/<uuid:pk>', pacientes.Editar.as_view(), name='editar'),
    path('eliminar/<uuid:pk>', pacientes.Eliminar.as_view(), name='eliminar'),
]

URL_OBSERVACIONES = [
    path('observaciones/<uuid:pk>', observaciones.Listar.as_view(), name='lista_observaciones'),
    path('observaciones/agregar/<uuid:pk>', observaciones.Agregar.as_view(), name='agregar_observacion'),
    path('observaciones/editar/<uuid:pk>', observaciones.Editar.as_view(), name='editar_observacion'),
    path('observaciones/eliminar/<uuid:pk>', observaciones.Eliminar.as_view(), name='eliminar_observacion')
]

URL_TURNOS = [
    path('turnos/', turnos.Listar.as_view(), name='lista_turnos'),
    path('turnos/agregar', turnos.Agregar.as_view(), name='agregar_turno'),
    path('turnos/editar/<uuid:pk>', turnos.Editar.as_view(), name='editar_turno'),
    path('turnos/eliminar/<uuid:pk>', turnos.Eliminar.as_view(), name='eliminar_turno')
]

urlpatterns = URLS_PACIENTES + URL_OBSERVACIONES + URL_TURNOS

pacientes/models/modelo_turno.py
# Django
from django.db import models
from django.utils import timezone

# Modelos
from compartido.modelo_base import ModeloBase
from . import Paciente

class Hora(ModeloBase):
    hora_cit = models.TextField(max_length=15)

    def __str__(self):
        return self.hora_cit

class Turno(ModeloBase):
    """
    Esta clase contiene la logica para persistir turnos en el sistema.
    El rol de Secretaria/Secretario es el encargado de administrar los pedidos.
    """
    
    ASISTIO_OPCIONES = (
        ('P', 'Pendiente'),
        ('A', 'Asistió'),
        ('F', 'Faltó')
    )

    paciente = models.ForeignKey(
        Paciente, 
        on_delete=models.CASCADE, 
        verbose_name="Paciente",
        related_name="turnos"
    ) 
    asistencia = models.CharField(
        max_length=1, 
        choices=ASISTIO_OPCIONES,  
        verbose_name="Asistencia",
        blank=True,
        null=True
    )
    time = models.ForeignKey(Hora, on_delete=models.CASCADE, verbose_name="Hora de la Cita")
    fecha = models.DateField(verbose_name="Día")


    class Meta:
        db_table = "turno"
        verbose_name = "Turno"
        verbose_name_plural = "Turnos"
    
    def __str__(self):
        return f"{self.paciente.nombre} {self.paciente.apellido}, {self.fecha}"

pacientes/views/turnos.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils import timezone
from django.views import generic

# Modelos
from ..models import Turno
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioTurno

class Listar(LoginRequiredMixin, generic.ListView):
    """
    Lista todos los turnos. 
    """
    model = Turno
    template_name = 'clinica/turnos/lista_turnos.html'
    context_object_name = 'Turnos'
    paginate_by = 5
    # page_kwarg

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Lista de turnos'
        contexto['buscar'] = 'Ingresa el nombre de alǵun paciente o una fecha'
        contexto['hoy'] = Turno.objects.filter(fecha=timezone.now()).filter(asistencia='P')
        return contexto


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega un nuevo turno y retorna a la lista de turnos.
    """
    model = Turno
    form_class = FormularioTurno
    template_name = 'clinica/turnos/form_turno.html'
    success_url = reverse_lazy('pacientes:lista_turnos')


    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Cargó un turno'
        )
        messages.success(
            self.request,
            'Turno cargado!'
        )
        form.instance.asistencia = Turno.ASISTIO_OPCIONES[0][0]  # P - PENDIENTE
        if not form.instance.fecha:
            form.instance.fecha = timezone.now()
        return super().form_valid(form)
 
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Registrar un nuevo turno'
        contexto['volver'] = self.success_url
        return contexto


class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de una determinada observacion
    """
    model = Turno
    form_class = FormularioTurno
    template_name = 'clinica/turnos/form_turno.html'
    success_url = reverse_lazy('pacientes:lista_turnos')

    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Modificó un turno'
        )
        messages.success(
            self.request,
            'Turno modificado!'
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Turno para {self.object.paciente}'
        contexto['url_volver'] = self.success_url
        contexto['editar'] = True
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """
    Elimina un turno.
    """
    model = Turno
    template_name = 'componentes/delete.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó un turno'
        )
        messages.success(
            self.request,
            'Turno eliminado!'
        )
        return reverse_lazy('pacientes:lista_turnos')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar el turno de {self.object.paciente}'
        contexto['url_volver'] = reverse_lazy('pacientes:lista_turnos')
        return contexto

templates/clinica/turnos/form_turno.html
{% extends 'layout.html' %}
{% load usuarios_tags %}
{% load widget_tweaks %}

{% block content %}
    {% if user|sector:"Secretaria" or user|sector:"Gerencia" %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container pt-3">
                <h1 class="display-5 text-center my-3">{{titulo}}</h1>
                
                {% include 'componentes/forms_errors.html' %}

                <div class="row d-flex justify-content-center my-5">
                    <!-- Paciente -->
                    <div class="col-md-4">
                        <div class="my-3">
                            <label class="form-label">
                                {{form.paciente.label|upper}}
                                <a href="{% url 'pacientes:agregar' %}?prev={{request.path}}" type="submit">
                                    <i class="fas fa-user-plus ml-3 text-success"></i>
                                </a>
                            </label>
                            {{form.paciente|attr:"autofocus:on"|attr:'autocomplete:off'|add_class:'form-control rounded-pill'}}
                        </div>
                    </div>
                    <!--  Fecha -->
                    <div class="col-md-4">
                        <div class="my-3">
                            <label class="form-label">{{form.fecha.label|upper}}</label>
                            {{form.fecha}}
                        </div>
                    </div>       
                    
                    <div class="col-md-4">
                        <div class="my-3">
                            <label class="form-label">{{form.time.label|upper}}</label>
                            {{form.time|add_class:'form-control rounded-pill'}}
                        </div>
                        </div>
                    </div>
                    <!--Fecha-->
                    <!-- <input id="datepicker" width="276" /> -->
                    
                    {% if editar %}
                        <!--  Estado -->
                        <div class="col-md-4">
                            <div class="my-3">
                                <label class="form-label">{{form.asistencia.label|upper}}</label>
                                {{form.asistencia|attr:"type:date"|add_class:'form-control rounded-pill'}}
                            </div>
                        </div>
                    {% endif %}
                </div>

                <div class="d-flex justify-content-center my-3">
                    <div class="btn-group shadow-sm" role="group" aria-label="Basic outlined example">
                        <a href="{% url 'pacientes:lista_turnos' %}" type="button" class="btn btn-outline-primary">
                            <i class="fas fa-angle-double-left text-info"></i> Volver
                        </a>
                        {% if editar %}
                            <a href="{% url 'pacientes:eliminar_turno' object.id %}" type="button" class="btn btn-outline-primary">
                                <i class="fas fa-times text-danger"></i> Cancelar
                            </a>
                        {% endif %}
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="fas fa-check text-ifno"></i> Guardar
                        </button>
                    </div>
                </div>
            </div>
        </form>
    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-8">
                <h1 class="text-center my-5 lead">No tienes permiso para cargar turnos</h1>
            </div>
        </div>
    {% endif %}

    
{% endblock %}

templates/clinica/turnos/lista_turnos.html
{% extends 'layout.html' %} 
{% load usuarios_tags %} 
{% load static %} 

{% block content %}
    {% if user|sector:"Secretaria" or user|sector:"Gerencia" %}
        {% include 'componentes/buscar_form.html' %}
        <div class="row">
            <div class="col-sm-3">
                <!-- Turnos del doctor -->
                <div class="my-3 p-3 bg-warning bg-gradient rounded shadow-lg">
                    <h3 class="text-center text-white py-3">
                    <!-- Chincheta -->
                    <img class="img-fluid" src="{% static 'img/cosito.svg' %}" alt="Cosito que apunta cosas" height="30" width="30">  
                    Hoy
                    {% if hoy %}
                        <span class="d-sm-none d-md-inline badge rounded-pill align-text-bottom" style="background-color: #C5A46F52;">
                            {{hoy.count}}
                        </span>
                    {% endif %}
                    </h3>
                    <!-- Pacientes para hoy que aún no fueron atentidos -->
                    {% if hoy %}
                        <ul class="list-group list-group-flush">
                            {% for turno in hoy %}
                                <li class="list-group-item bg-transparent">{{turno.paciente}}</li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>No hay turnos pendientes para hoy</p>
                    {% endif %}
                    <!---->
                </div>
            </div>

            <div class="col-sm-9">
                <div class="table-responsive bg-white my-3 p-3 rounded shadow-lg">
                    <div class="row mb-2">
                        <div class="col-6">
                            <h6 class="border-bottom pb-2 mb-0">
                                {{titulo}}
                                {% if Turnos %}
                                <span class="badge bg-warning rounded-pill align-text-bottom">{{Turnos.count}}</span>
                                {% endif %}
                            </h6>
                        </div>
                        <div class="col-6">
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <a type="buttom" class="btn btn-success btn-sm text-dark" 
                                href="{% url 'pacientes:agregar_turno' %}">
                                    <i class="fas fa-plus"></i>
                                    Agregar
                                </a>
                            </div>
                        </div>
                    </div>
                    {% if Turnos %}
                        <table class="table display table-bordered  table-striped table-hover table-sm id" class="stripe row-border order-column nowrap">
                            <thead>
                                <tr class="table-primary text-center">
                                    <th>Paciente</th>
                                    <th>Fecha</th>
                                    <th>Hora</th>
                                    <th>Asistencia</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for turno in Turnos %}
                                    <tr class="text-center">
                                        <td>{{turno.paciente}}</td>
                                        <td>           
                                            {{turno.fecha}}
                                        </td>
                                        <td>           
                                            {{turno.time}}
                                        </td>
                                        <td>
                                            {{turno.get_asistencia_display}}
                                        </td>
                                        <td>
                                            <a class="btn btn-sm d-flex align-self-center" 
                                            href="{% url 'pacientes:editar_turno' turno.id %}">
                                            <i class="fas fa-edit"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %} 
                            </tbody>
                        </table>
                    {% else %}
                        <h1 class="text-center my-3 lead">No hay turnos aún</h1>
                    {% endif %}
                </div>
                {% include 'componentes/paginacion.html' %}
            </div>
        </div>
    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-8">
                <h1 class="text-center my-5 lead">No tienes permiso para ver los turnos</h1>
            </div>
        </div>
    {% endif %}
{% endblock %}