clinica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('', include('compartido.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

compartido/urls.py
# Django
from django.urls import path

# Vistas
from .vistas import HomeView

app_name = 'compartido'

urlpatterns=[
    #...home, about, contact
    path('', HomeView, name='inicio')
]

productos/urls.py
# Django
from django.urls import path

# Vistas
from .views import productos, pedidos, detallePedidos as detalles, categorias

app_name = 'productos'

URLS_PRODUCTOS = [
    path('', productos.Listar.as_view(), name='lista'),
    path('agregar/', productos.Agregar.as_view(), name='agregar'),
    path('detalle/<uuid:pk>', productos.Detalle.as_view(), name='detalle'),
    path('editar/<uuid:pk>', productos.Editar.as_view(), name='editar'),
    path('eliminar/<uuid:pk>', productos.Eliminar.as_view(), name='eliminar'),
]

URLS_CATEGORIAS = [
    path('categorias/', categorias.Agregar.as_view(), name='categorias'),
    path('categorias/editar/<int:pk>', categorias.Editar.as_view(), name='editar_categoria'),
    path('categorias/eliminar/<int:pk>', categorias.Eliminar.as_view(), name='eliminar_categoria')
]


URLS_PEDIDOS = [
    path('pedidos/', pedidos.Listar.as_view(), name='lista_pedidos'),
    path('pedidos/agregar/', pedidos.Agregar.as_view(), name='agregar_pedido'),
    path('pedidos/editar/<uuid:pk>', pedidos.Editar.as_view(), name='editar_pedido'),
    path('pedidos/eliminar/<uuid:pk>', pedidos.Eliminar.as_view(), name='eliminar_pedido')
]

URLS_DETALLES = [
    path('pedidos/agregar_producto/<uuid:pk>', detalles.Agregar.as_view(), name='agregar_detalle'),
    path('pedidos/eliminar_producto/<uuid:pk>', detalles.Eliminar.as_view(), name='eliminar_detalle'),
    path('pedidos/editar_producto/<uuid:pk>', detalles.Editar.as_view(), name='editar_detalle')
]

urlpatterns = URLS_PRODUCTOS + URLS_CATEGORIAS + URLS_PEDIDOS + URLS_DETALLES

usuarios/urls.py
# Django
from django.urls import path

# Vistas
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('', IniciarSesion.as_view(), name='entrar'),
    path('salir/', LogoutView.as_view(), name='salir'),
    path('crear/', CrearUsuario.as_view(), name='crear'),
    path('lista/', ListaUsuarios.as_view(), name='lista'),
    path('actividades/', ListaActividades.as_view(), name='actividades'),
    path('editar/<int:pk>/', EditUsuario.as_view(), name='editar'),
     path('eliminar/<int:pk>/', EliminarUsuario.as_view(), name='eliminar')


]

usuarios/models.py
# Django
from django.db import models
from django.forms import model_to_dict
from django.utils import timezone

# Modelos
from django.contrib.auth.models import AbstractUser, Group

ROL_OPCIONES = (
    ('M', 'Medico'),  
    ('S', 'Secretaria'),  
    ('G', 'Gerencia'), 
    ('V', 'Venta'), 
    ('T', 'Taller') 
)

class Usuario(AbstractUser):
    imagen = models.ImageField(upload_to='usuarios/img', blank=True, null=True, verbose_name="Imagen")
    rol = models.CharField(max_length=1, default='S', choices=ROL_OPCIONES, verbose_name="Sector")
    dni = models.CharField(max_length=11, verbose_name="Documento")
    # nombre = models.CharField(max_length=25, verbose_name="Nombre")
    # apellido = models.CharField(max_length=25, verbose_name="Apellido")
    ultima_actividad = models.DateTimeField(verbose_name="Última actividad", blank=True, null=True)

    

    def __str__(self):
        return self.first_name +' '+ self.last_name
    
    # def toJSON(self):
    #     item = model_to_dict(self, exclude=['password','user_permissions', 'last_login'])
    #     if self.last_login:
    #         #  item['last_login'] = self.last_login.strftime('%Y-%m-%d')
    #     # item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
    #     # item['image'] = self.get_image()
    #     item['full_name'] = self.get_full_name()
    #     item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
    #     return item


class Actividad(models.Model):
    """
    Cada interación con el sistema por parte de los empleados
    registrará una nueva actividad. 
    """
    accion = models.CharField(max_length=100, verbose_name="Acción")
    # No hago una relación con usuarios porque solo quiero registrar el nombre
    # y que persista independientemente de que el usuario sea borrado.
    # Si pongo on_delete=models.SET_NULL lo mismo necesitaria este campo.
    # Directamente uso solo este campo
    usuario = models.CharField(max_length=100, verbose_name="Usuario")
    momento = models.DateTimeField(verbose_name="Momento de la acción")

    def __str__(self):
        return self.acccion


def registrarActividad(request, mensaje):
    u_username = request.user.username
    u_nombre = f'{request.user.first_name} {request.user.last_name}'
    u_dni = request.user.dni
    usuario_actual = f'{u_username}, {u_nombre}, {u_dni}'
    accion_actual = mensaje
    Actividad.objects.create(accion=accion_actual, usuario=usuario_actual, momento=timezone.now())
    usuario_actual = Usuario.objects.get(id=request.user.id)
    usuario_actual.ultima_actividad = timezone.now()
    usuario_actual.save()

usuarios/forms.py
# Django
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import ModelForm
from django.forms.widgets import PasswordInput

# Modelos
from .models import Usuario

class FormularioUsuario(ModelForm):

    class Meta:
        model = Usuario
        fields = '__all__'
        widgets ={

        'password': PasswordInput(render_value=True,
                                      attrs={
                                          'placeholder': 'Ingrese su password',
                                      }
                                      ),
                                      
         
        }
        

        exclude = ['user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_active', 'is_staff']

    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = Usuario.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password(pwd)
                u.save()
                u.groups.clear()
                for g in self.cleaned_data['groups']:
                    u.groups.add(g)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

usuarios/views.py
# Django
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.utils.timezone import localtime, now
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import DeleteView, UpdateView


# Modelos
from .models import Usuario, ROL_OPCIONES, Actividad
from django.contrib.auth.models import Group
from usuarios.models import registrarActividad

# Formularios
from .forms import FormularioUsuario

class IniciarSesion(LoginView):
    template_name = 'clinica/usuarios/inicio_de_sesion.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('compartido:inicio')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        usuario = self.request.user.username
        ultima_vez = localtime(self.request.user.last_login).date()
        fecha_registro = localtime(self.request.user.date_joined).date()
        if fecha_registro == ultima_vez:
            messages.success(
                self.request,
                f'Hola {usuario}! que tengas un productivo primer dia en el sistema! 🥳'
            )
        else:
            messages.success(
                self.request,
                f'Hola {usuario}! entraste por ultima vez el {ultima_vez}'
            )
        if self.request.user.groups.exists():
            grupo = self.request.user.groups.get()
            if grupo.name == ROL_OPCIONES[0][1]:
                # Medico
                return reverse_lazy('pacientes:lista')
            elif grupo.name == ROL_OPCIONES[1][1]:  
                # SECRETARIA
                return reverse_lazy('pacientes:lista_turnos')
            elif grupo.name == ROL_OPCIONES[2][1]:  
                # Gerencia
                return reverse_lazy('productos:lista')
            elif grupo.name == ROL_OPCIONES[3][1]:  
                # Venta
                return reverse_lazy('productos:lista_pedidos')
            elif grupo.name == ROL_OPCIONES[4][1]:  
                # Taller
                return reverse_lazy('productos:lista_pedidos')
        return reverse_lazy('productos:lista')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['titulo'] = 'Iniciar Sesión'
        return ctx


class CrearUsuario(generic.CreateView):
    model = Usuario
    form_class = FormularioUsuario
    template_name = 'clinica/usuarios/form_usuario.html'
    # permission_required = 'user.add_user'

    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return redirect('compartido:inicio')
    #     return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.is_staff = True
        form.instance.is_active = True
        return super().form_valid(form)
    
    def get_success_url(self):
        nombre_usuario = self.request.POST.get('username')
        usuario = Usuario.objects.get(username=nombre_usuario)
        grupo = Group.objects.get(name=usuario.get_rol_display())
        usuario.groups.add(grupo.id)
        messages.success(
            self.request,
            f'Usuario {nombre_usuario} registrado!'
        )
        return reverse_lazy('usuarios:listar')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['titulo'] = 'Crear usuario'
        return ctx


class ListaActividades(generic.ListView):
    queryset = Actividad.objects.order_by('-id')
    template_name = 'clinica/usuarios/actividades.html'
    context_object_name = 'Actividades'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['titulo'] = 'Registro de actividades'
        ctx['buscar'] = 'Nombre de usuario o actividad'
        return ctx


class ListaUsuarios(generic.ListView):
    queryset = Usuario.objects.order_by('-date_joined')
    template_name = 'clinica/usuarios/lista_usuarios.html'
    context_object_name = 'Usuarios'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['titulo'] = 'Lista de usuarios'
        ctx['buscar'] = 'Nombre de usuario o sector'
        return ctx


class EditUsuario(LoginRequiredMixin, UpdateView):
    model = Usuario
    form_class = FormularioUsuario
    template_name = 'clinica/usuarios/form_usuario.html'
    success_url = reverse_lazy('usuarios:lista')
    permission_required = 'user.change_user'
    permission_required = 'user.add_user'
    url_redirect = success_url

    def form_valid(self, form):
        form.instance.is_staff = True
        form.instance.is_active = True
        return super().form_valid(form)
    
    def get_success_url(self):
        nombre_usuario = self.request.POST.get('username')
        usuario = Usuario.objects.get(username=nombre_usuario)
        grupo = Group.objects.get(name=usuario.get_rol_display())
        usuario.groups.add(grupo.id)
        messages.success(
            self.request,
            f'Usuario {nombre_usuario} actualizado!'
        )
        return reverse_lazy('usuarios:lista')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['titulo'] = 'Editando Usuario'
        return ctx

class EliminarUsuario(LoginRequiredMixin, DeleteView):
    model = Usuario
    template_name = 'clinica/usuarios/delete.html'
    success_url = reverse_lazy('usuarios:lista')
    permission_required = 'user.delete_user'
    url_redirect = success_url

    # def dispatch(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     return super().dispatch(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     data = {}
    #     try:
    #         self.object.delete()
    #     except Exception as e:
    #         data['error'] = str(e)
    #     return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminando  un Usuario'
        context['entity'] = 'Usuarios'
        context['list_url'] = self.success_url
        return context

templates/clinica/usuarios/actividades.html
{% extends 'layout.html' %} 
{% load usuarios_tags %}
{% load static %} 

{% block content %}
  {% if user|sector:"Gerencia" %}
    {% include 'componentes/buscar_form.html' %}
    <div class="row d-flex justify-content-center">

      <div class="col-sm-8">
        <div class="my-3 p-3 bg-white rounded shadow-lg">
          
          <div class="row text-center">
              <h6 class="border-bottom pb-2 mb-0">
                {{titulo}}
              </h6>
          </div>
          
          {% if Actividades %}
            <div class="table-responsive my-3">
              <table  class="table display table-bordered  table-striped table-hover table-sm id" class="stripe row-border order-column nowrap">
                <thead class="text-primary">
                  <tr class="table-primary">
                    <th>
                        <span class="border-bottom border-verde border-3">
                            Empleado
                        </span>
                    </th>
                    <th>Acción</th>
                    <th class="text-center">Momento</th>
                  </tr>
                </thead>
                <tbody>
                  {% for actividad in Actividades %}
                    <tr>
                        <td>
                            {{actividad.usuario}}
                        </td>
                        <td>
                            {{actividad.accion}}
                        </td>
                        <td class="text-center">
                            {{actividad.momento|date:"D d M P"}}
                        </td>
                    </tr>
                    {% endfor %} 
                </tbody>
              </table>
            </div>
          {% else %}
              <h1 class="text-center my-3 lead">No hay actividades aún</h1>
          {% endif %}
        </div>
        {% include 'componentes/paginacion.html' %}
      </div>
    </div>
  {% else %}
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center my-5 lead">No tienes permiso para ver la lista de usuarios</h1>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/clinica/usuarios/delete.html
{% extends 'layout.html' %} 
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Estas seguro de eliminar el registro: {{ object}}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                Swal.fire({
                    title: 'Alerta',
                    text: 'Registro eliminado correctamente',
                    icon: 'success',
                    timer: 2000,
                    onClose: () => {
                        location.href = '{{ list_url }}';
                    }
                }).then((result) => {

                });
            });
        });
    </script>
{% endblock %}

templates/clinica/usuarios/form_usuario.html
{% extends 'layout.html' %}
{% load widget_tweaks %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container pt-3">
            <h1 class="display-5 text-center my-3">{{titulo}}</h1>
            
            {% include 'componentes/forms_errors.html' %}

            <div class="row">
                <!-- username -->
                <div class="col-md-3">
                    <div class="my-3">
                        <label class="form-label">
                            {{form.username.label|upper}}
                            <span class="text-danger">*</span>
                        </label>
                        {{form.username|attr:"autocomplete:off"|attr:"autofocus:on"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
                <!-- password -->
                <div class="col-md-3">
                    <div class="my-3">
                        <label class="form-label">
                            {{form.password.label|upper}}
                            <span class="text-danger">*</span>
                        </label>
                        {{form.password|attr:"type:password"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
        
                 <!-- password2 -->
                <div class="col-md-3">
                    <div class="my-3">
                        <label class="form-label">
                            {{form.password.label|upper}}
                            <span class="text-danger">*</span>
                        </label>
                        {{form.password|attr:"type:password"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>

                <!-- rol -->
                <div class="col-md-3">
                    <div class="my-3">
                        <label class="form-label">{{form.rol.label|upper}}</label>
                        {{form.rol|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Nombre -->
                <div class="col-sm-4">
                    <div class="my-3">
                        <label class="form-label">
                            {{form.first_name.label|upper}}
                            <span class="text-danger">*</span>
                        </label>
                        {{form.first_name|attr:"autocomplete:off"|attr:"autofocus:on"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
                <!-- Apellido -->
                <div class="col-sm-4">
                    <div class="my-3">
                        <label class="form-label">
                            {{form.last_name.label|upper}}
                            <span class="text-danger">*</span>
                        </label>
                        {{form.last_name|attr:"autocomplete:off"|attr:"autofocus:on"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
                <!-- Imagen -->
                <div class="col-sm-4">
                    {% if object.imagen %}
                        <div class="my-3">
                            <label class="form-label">{{form.imagen.label|upper}}</label>
                            <img src="{{object.imagen.url}}" class="img-fluid" alt="Imagen" height="60" width="60">
                            {{form.imagen|attr:"type:file"|add_class:'py-3'}}
                        </div>
                    {% else %}
                        <div class="form-file mt-md-5 my-3">
                            {{form.imagen|attr:"type:file"|add_class:'form-file-input'}}
                            <label class="form-file-label" for="customFile">
                                <span class="form-file-text">{{form.imagen.label|upper}}</span>
                                <span class="form-file-button">Buscar</span>
                            </label>
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="row d-flex justify-content-center">
                <!--  Email -->
                <div class="col-sm-4">
                    <div class="my-2">
                        <label class="form-label">{{form.email.label|upper}}</label>
                        {{form.email|attr:"type:email"|attr:"autocomplete:off"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="my-2">
                        <label class="form-label">
                            {{form.dni.label|upper}}
                            <span class="text-danger">*</span>
                        </label>
                        {{form.dni|attr:"autocomplete:off"|add_class:'form-control rounded-pill'}}
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-center my-4">
                <div class="btn-group shadow-sm" role="group" aria-label="Basic outlined example">
                    {% if editar %}
                        <a href="{% url 'productos:detalle' producto.id %}" type="button" class="btn btn-outline-primary"><i class="fas fa-angle-double-left text-info"></i> Volver</a>
                    {% else %}
                        <a href="{% url 'productos:lista' %}" type="button" class="btn btn-outline-primary">
                            <i class="fas fa-angle-double-left text-info"></i> Volver
                        </a>
                    {% endif %}
                    <button type="submit" class="btn btn-outline-primary">
                        <i class="fas fa-check text-ifno"></i> Guardar
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/clinica/usuarios/inicio_de_sesion.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'libs/bootstrap/signin.css' %}" />
{% endblock %} 

{% block aplicacion %}

  <nav class="navbar fixed-top navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'compartido:inicio' %}">
        <img src="{% static 'favicon/favicon-32x32.png' %}" alt="Logo">
      </a>
    </div>
  </nav>
  
  
  <main class="form-signin text-center">
    {% include 'componentes/forms_errors.html' %}
    {% include 'componentes/mensajes.html' %}
    <form method="POST">
        {% csrf_token %}
        <img class="img-fluid" src="{% static 'img/login.svg' %}" alt="login" width="100" height="100">
        <br>        
        <!--Usuario-->
        <label class="form-label my-3 border-bottom border-verde border-3">
          {{form.username.label|lower}}
        </label>
        {{form.username|attr:"autocomplete:off"|attr:"placeholder:Escriba su nombre de usuario"|attr:"autofocus:on"|add_class:'form-control rounded'}}
        
        <!--Password-->
        <label class="form-label my-3 border-bottom border-verde border-3">
          {{form.password.label|lower}}
        </label>
        {{form.password|attr:"type:password"|attr:"placeholder:Escriba su contraseña"|add_class:'form-control rounded'}}
        
        <div class="d-grid gap-2 col-12 my-4 mx-auto">
          <button type="submit" class="btn btn-primary">
            <i class="fas fa-sign-in-alt"></i> ENTRAR
          </button>
      </div>
      <a class="text-muted" href="{% url 'usuarios:crear' %}" style="text-decoration: none;">Crear cuenta</a>
    </form>
    {% include 'componentes/footer.html' %}
  </main>
{% endblock %}

templates/clinica/usuarios/lista_usuarios.html
{% extends 'layout.html' %} 
{% load widget_tweaks %}
{% load usuarios_tags %}
{% load static %} 

{% block content %}
  {% if user|sector:"Gerencia" %}
    {% include 'componentes/buscar_form.html' %}
    <div class="row d-flex justify-content-center">

      <div class="col-sm-8">
        <div class="my-3 p-3 bg-white rounded shadow-lg">
          
          <div class="row text-center">
              <h6 class="border-bottom pb-2 mb-0">
                {{titulo}}
                {% if Usuarios %}
                    <span class="badge bg-warning rounded-pill align-text-bottom">
                        {{Usuarios.count}}
                    </span>
                {% endif %}
              </h6>
          </div>
          
          {% if Usuarios %}
            <div class="table-responsive my-3">
              <table class="table display table-bordered table-striped table table-hover table-borderless table-hover table-sm id " >
                <thead class="text-primary">
                  <tr class="table-primary"> 
                    <th>
                        <span class="border-bottom border-verde border-3">
                            Usuario
                        </span>
                    </th>
                    <th>Sector</th>
                    <th class="text-center">Act.Reciente</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for usuario in Usuarios %}
                    <tr>
                        <td>
                            {{usuario.username}}
                        </td>
                        <td>
                            {{usuario.get_rol_display}}
                        </td>
                        <td class="text-center">
                            {% if usuario.ultima_actividad %}
                                {{usuario.ultima_actividad}}
                            {% else %}
                                Ningúna
                            {% endif %}
                        </td>
                        <td>
                        <a href="{% url 'usuarios:editar' usuario.id%}" class="float-right mr-3">
                          <i class="fas fa-user text-primary"></i>
                        </a>
                        </td>
                        <td>
                        <a href="{% url 'usuarios:eliminar' usuario.id%}" class="text-center">
                          <i class="fas fa-times text-danger"></i>
                        </a>
                      </td>
                    </tr>
                    {% endfor %} 
                </tbody>
              </table>
               <div class="col-md-6">
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <a type="buttom" class="btn btn-success btn-sm text-dark" href="{% url 'usuarios:crear' %}">
                            <i class="fas fa-plus"></i>
                            Agregar
                        </a>
                    </div>
                </div>
            </div>
          {% else %}
              <h1 class="text-center my-3 lead">No hay usuarios aún</h1>
          {% endif %}
        </div>
        {% include 'componentes/paginacion.html' %}
      </div>
    </div>
  {% else %}
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center my-5 lead">No tienes permiso para ver la lista de usuarios</h1>
      </div>
    </div>
  {% endif %}
{% endblock %}