clinica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('', include('compartido.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pacientes/urls.py
# Django
from django.urls import path

# Vistas

from .views import pacientes, observaciones, turnos

app_name = 'pacientes'

URLS_PACIENTES = [
    path('', pacientes.Listar.as_view(), name='lista'),
    path('agregar/', pacientes.Agregar.as_view(), name='agregar'),
    path('detalle/<uuid:pk>', pacientes.Detalle.as_view(), name='detalle'),
    path('editar/<uuid:pk>', pacientes.Editar.as_view(), name='editar'),
    path('eliminar/<uuid:pk>', pacientes.Eliminar.as_view(), name='eliminar'),
]

URL_OBSERVACIONES = [
    path('observaciones/<uuid:pk>', observaciones.Listar.as_view(), name='lista_observaciones'),
    path('observaciones/agregar/<uuid:pk>', observaciones.Agregar.as_view(), name='agregar_observacion'),
    path('observaciones/editar/<uuid:pk>', observaciones.Editar.as_view(), name='editar_observacion'),
    path('observaciones/eliminar/<uuid:pk>', observaciones.Eliminar.as_view(), name='eliminar_observacion')
]

URL_TURNOS = [
    path('turnos/', turnos.Listar.as_view(), name='lista_turnos'),
    path('turnos/agregar', turnos.Agregar.as_view(), name='agregar_turno'),
    path('turnos/editar/<uuid:pk>', turnos.Editar.as_view(), name='editar_turno'),
    path('turnos/eliminar/<uuid:pk>', turnos.Eliminar.as_view(), name='eliminar_turno')
]

urlpatterns = URLS_PACIENTES + URL_OBSERVACIONES + URL_TURNOS

productos/urls.py
# Django
from django.urls import path

# Vistas
from .views import productos, pedidos, detallePedidos as detalles, categorias

app_name = 'productos'

URLS_PRODUCTOS = [
    path('', productos.Listar.as_view(), name='lista'),
    path('agregar/', productos.Agregar.as_view(), name='agregar'),
    path('detalle/<uuid:pk>', productos.Detalle.as_view(), name='detalle'),
    path('editar/<uuid:pk>', productos.Editar.as_view(), name='editar'),
    path('eliminar/<uuid:pk>', productos.Eliminar.as_view(), name='eliminar'),
]

URLS_CATEGORIAS = [
    path('categorias/', categorias.Agregar.as_view(), name='categorias'),
    path('categorias/editar/<int:pk>', categorias.Editar.as_view(), name='editar_categoria'),
    path('categorias/eliminar/<int:pk>', categorias.Eliminar.as_view(), name='eliminar_categoria')
]


URLS_PEDIDOS = [
    path('pedidos/', pedidos.Listar.as_view(), name='lista_pedidos'),
    path('pedidos/agregar/', pedidos.Agregar.as_view(), name='agregar_pedido'),
    path('pedidos/editar/<uuid:pk>', pedidos.Editar.as_view(), name='editar_pedido'),
    path('pedidos/eliminar/<uuid:pk>', pedidos.Eliminar.as_view(), name='eliminar_pedido')
]

URLS_DETALLES = [
    path('pedidos/agregar_producto/<uuid:pk>', detalles.Agregar.as_view(), name='agregar_detalle'),
    path('pedidos/eliminar_producto/<uuid:pk>', detalles.Eliminar.as_view(), name='eliminar_detalle'),
    path('pedidos/editar_producto/<uuid:pk>', detalles.Editar.as_view(), name='editar_detalle')
]

urlpatterns = URLS_PRODUCTOS + URLS_CATEGORIAS + URLS_PEDIDOS + URLS_DETALLES

reportes/urls.py
# Django
from django.urls import path

# Vistas
from .views import ListaPacientes, ListaVentasPorMes, descargarPDF

app_name = 'reportes'

urlpatterns = [
    path('pacientes/',ListaPacientes.as_view(), name='pacientes'),
    path('ventas/', ListaVentasPorMes.as_view(), name='ventas'),
    path('descargar/', descargarPDF, name='descargar')
]

usuarios/urls.py
# Django
from django.urls import path

# Vistas
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('', IniciarSesion.as_view(), name='entrar'),
    path('salir/', LogoutView.as_view(), name='salir'),
    path('crear/', CrearUsuario.as_view(), name='crear'),
    path('lista/', ListaUsuarios.as_view(), name='lista'),
    path('actividades/', ListaActividades.as_view(), name='actividades'),
    path('editar/<int:pk>/', EditUsuario.as_view(), name='editar'),
     path('eliminar/<int:pk>/', EliminarUsuario.as_view(), name='eliminar')


]

templates/componentes/buscar_form.html
<form class="d-flex">
  <input class="form-control mr-2" autocomplete="off" type="search" placeholder="{{buscar}}" aria-label="Search" name="query">
  <button class="btn btn-outline-success text-dark" type="submit">Buscar</button>
</form>

templates/componentes/delete.html
{% extends 'layout.html' %} 
{% block content %}
  <div class="row my-3">
    <h1 class="text-center my-3">
      ¿Estás seguro de <span class="border-bottom border-danger border-3">{{titulo|lower}}</span>?
    </h1>
    <div class="d-flex justify-content-center align-items-center">
      <form method="post">
        {% csrf_token %}
        <div class="btn-group shadow-sm my-3" role="group" aria-label="Basic outlined example">
          
          <a href={{url_volver}} type="button" class="btn btn-outline-primary">
            <i class="fas fa-angle-double-left text-info"></i> Volver
          </a>

          <button type="submit" class="btn btn-outline-primary">
            <i class="fas fa-check text-info"></i> Confirmar
          </button>

        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/componentes/footer.html
<div class="footer-basic">
  <footer>
    <h1 class="copyright">Abel | Soriano</h1>
  </footer>
</div>

templates/componentes/forms_errors.html
{% if form.errors %}
    <div class="row">
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{field.label_tag}} {{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{field.label_tag}} {{ error|escape }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/componentes/mensajes.html
{% for message in messages %}
    <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
        <h1 class="text-center lead">
            {{message}}
        </h1>
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

templates/componentes/nav.html
{% load static %}
{% load usuarios_tags %}
<nav
  class="navbar navbar-expand-lg fixed-top navbar-light bg-light" aria-label="Main navigation">
  <div class="container-fluid">
    
    <a class="navbar-brand" href="{% url 'compartido:inicio' %}">
      <img src="{% static 'favicon/favicon-32x32.png' %}" alt="Logo">
    </a>
    
    <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse open bg-light text-center" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        
        {% if user|sector:"Medico" or user|sector:"Secretaria" or user|sector:"Gerencia" %}
          <li class="nav-item active my-2">
            <a class="nav-link" aria-current="page" href="{% url 'pacientes:lista' %}">
              PACIENTES
            </a>
          </li>
        {% endif %}

        {% if user|sector:"Secretaria" or user|sector:"Gerencia" %}
          <li class="nav-item my-2">
            <a class="nav-link" href="{% url 'pacientes:lista_turnos' %}">
              TURNOS
            </a>
          </li>
        {% endif %}
        
        {% if user|sector:"Venta" or user|sector:"Gerencia" %}
        <li class="nav-item my-2">
          <a class="nav-link" href="{% url 'productos:lista' %}">
            PRODUCTOS
          </a>
        </li>
        <li class="nav-item my-2">
          <a class="nav-link" href="{% url 'productos:categorias' %}">
            CATEGORIAS
          </a>
        </li>
        {% endif %}

        {% if user|sector:"Venta" or user|sector:"Taller" or user|sector:"Gerencia" %}
        <li class="nav-item my-2">
          <a class="nav-link" href="{% url 'productos:lista_pedidos' %}">
            PEDIDOS
          </a>
        </li>
        {% endif %}

        {% if user|sector:"Gerencia" %}
        <li class="nav-item my-2">
          <a class="nav-link" href="{% url 'usuarios:lista' %}">
            USUARIOS
          </a>
        </li>
        <li class="nav-item my-2">
          <a class="nav-link" href="{% url 'usuarios:actividades' %}">
            HISTORIAL
          </a>
        </li>
        <li class="nav-item my-2">
          <div class="dropdown">
            <button class="btn btn-transparent dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
              <span class="border-bottom border-verde border-3">Reportes</span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><a class="dropdown-item" href="{% url 'reportes:pacientes' %}">Pacientes</a></li>
              <li><a class="dropdown-item" href="{% url 'reportes:ventas' %}">Ventas</a></li>
            </ul>
          </div>
        </li>
        {% endif %}
      </ul>

      <a href="{% url 'usuarios:salir' %}">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout my-2" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
          <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />
          <path d="M7 12h14l-3 -3m0 6l3 -3" />
        </svg>
      </a>
    </div>
  </div>
</nav>

templates/componentes/paginacion.html
{% if is_paginated %}
    <nav aria-label="Page navigation conatiner">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li>
                    <a class="btn btn-sm" href="?page={{ page_obj.previous_page_number }}" class="page-link">
                    <i class="fas fa-angle-double-left text-primary"></i>
                    </a>
                </li>
            {% endif %}
            {% if page_obj.has_next %}
                <li>
                    <a class="btn btn-sm" href="?page={{ page_obj.next_page_number }}" class="page-link">
                    <i class="fas fa-angle-double-right text-primary"></i>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/componentes/subnav.html
{% if user.is_authenticated %}
  <div class="nav-scroller bg-white shadow-sm">
    <nav class="nav nav-underline d-flex justify-content-center" aria-label="Secondary navigation">
      <a class="nav-link active" aria-current="page" href="#" id="subnav">
        <i class="fas fa-circle text-verde mr-2"></i>
        {{user.username|upper}} | {{date}}
      </a>
    </nav>
  </div>
{% endif %}